### ISSUE TITLE
Android: stay logged in v2

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#89]
The old version used a foreground service. Everyone hated the icon, so I tried a background service. It just gets killed when the app gets killed.

So now I think using the [AccountManager](https://developer.android.com/reference/android/accounts/AccountManager) is the way to go. This will have similar guarantees as the desktop stay logged in (#49) feature, which is to say, don't use it unless you have an encrypted drive or you really don't care about your account's security.

I'm fine making this tradeoff if the users are (and they seem to want it).

Needs a big, fat warning!

## Blocked by
- #90

**Comment by orthecreedence** [comment]
Ok, looks like we actually want [Keystore](https://developer.android.com/training/articles/keystore#UsingAndroidKeyStore), not AccountManager. The idea is we'd save our login, use Keystore to encrypt the key for the saved login, then store that encrypted key in the app's prefs.

**Comment by opensource21** [comment]
I'm experienced Java-developer with small Android Know-How. Can I help you to get this solved?

**Comment by orthecreedence** [comment]
Yes, I would love that. Right now I'm working on another aspect of the app and I have limited time to work on the Anrdoid portion of things, so any help would be greatly appreciated.

So I think the general plan for this is to build a Java/Android class that:

1. Receives an an unencrypted key that needs to be encrypted.
1. Android's Keystore is used to encrypt the unencrypted key.
1. The encrypted key is stored in the app settings and can be recalled later.

This would be to save a login. To restore a login, the Java class:

1. Recalls the encrypted key from the app settings.
1. If an encrypted key is found, uses Keystore to decrypt the key (if not key found returns null? not sure what's idiomatic for Java)
1. Returns the decrypted key to the caller.

Does that sound right? I'm not an expert on this, so any input would be helpful.

Thanks!

**Comment by opensource21** [comment]
Sound's good. Just to get the use case more clear. In the previous version the "stay logged in"-feature solves two purposes:

- convenient - you don't need to logged in every time you use the app.
- offline-usage - if you was in a region with no internet you should be able to get access to your data.

If I understand the new "rust"-solution correct the offline-usage is solved independent from the issue. So we only talk abut the convenient aspect. Am I right?

About the interace-definition of such class. The unencrypted key is a byte-array right?

Can you provide the minimum android-version you want to provide. Android 4.3 (API level 18) needed to use the Keystore or Android 6 (API 23) would support more modern encryption?

I hope I find time the next weeks to create a solution.

**Comment by orthecreedence** [comment]
I think API 23 is the earliest we care about, which from what I read about Keystore should simplify things a bit. Yes, unencrypted key would be a byte array. I'll most likely build a cordova plugin around this class and I can handle any conversion needed to call into it.

The rust portion of the app still does not have full offline mode (tracked here: #61) so this will be about continued offline usage as well as convenience (but either way I don't think this will change the interface so we shouldn't have to worry too much about it).

Thanks for your help!

**Comment by opensource21** [comment]
I started today. You can see the result [in a separate project](https://github.com/opensource21/TurtlSecretStoreExample/blob/master/app/src/main/java/com/lyonbros/turtlcore/SecurityStore.java). 
I want to make the possibility to have a secure solution. So there are 3 modes:
NONE - There is no extra protection to get the key -> works
AUTHENTICATION - Ensures that the user has authenticated a few minutes before.
PASSWD - Ask for a separate password, so you can use a simple password like 123 to protect the stored key.

The last two variants needs some extra work. But I think I the api will be the same.
Any feedback is welcome.
Niels

**Comment by opensource21** [comment]
It looks like the AUTHENTICATION Method with is recommended is more tricky than it looks. Found [failure report](https://stackoverflow.com/questions/36043912/error-after-fingerprint-touched-on-samsung-phones-android-security-keystoreexce). So I think if you look at the increase of security (check that user has authenticated 5 minutes before) and the probability that we must handle obscure error-reports  which only happens on some devices, I would recommend to remove this feature. 
@orthecreedence  What do you think?

**Comment by opensource21** [comment]
The idea to make a second password to crypt the stored keys with a weaker password than the original, can't be  handle with the current api. The android ui is non-blocking so we must  use a callback.  This can be done, but it's difficult to test and to understand. One possibility is that the password is given from the JS-Part.  Then we need a class for en- and decrypt.  A method which can be asked if the return is encrypted.
I really would love to see this feature, because it's enable to have short password on my device and a complex-password for the internet (Keypass2Android has such a feature). After 1 mistake I must enter my complex-password. It's a nice combination of security and convenience.
I would recommend to create a ticket for the extra protection and remove all security-features from my class. Then I can integrate it into the existing Cordova-Plugin and we can close this issue.

Waiting on your feedback.

**Comment by opensource21** [comment]
Created a [turtl-branch](https://github.com/opensource21/TurtlSecretStoreExample/blob/turtl/app/src/main/java/com/lyonbros/turtlcore/SecurityStore.java) with  simplified version

**Comment by orthecreedence** [comment]
@opensource21 the solution you came up with is the exact one I imagined for this particular feature: no secondary password at all, just using the built-in security features of the OS to protect the login key. The "stay logged in" feature comes with a big warning no matter what platform, so I think we can be more lax on security for now. 

Also, sorry for the late response, I was traveling last week.
